services:
  api:
    image: geonmagno/api_patient:0.1.0
    container_name: api_patient_test
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword;"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_patient
    restart: always
    environment:
      POSTGRES_DB: "mydatabase"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
